# Generated by Django 6.0 on 2025-12-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choices_text',
            new_name='choice_text',
        ),
    ]
